name: woven-app
version: 0.0.2
dependencies:
  angular: 0.12.0
  angular_node_bind: any
  shadow_dom: any
  browser: any
  polymer: ">=0.11.0 <0.12.0"
  core_elements: ">=0.0.6 <0.1.0"
  firebase: ">=0.1.0 <0.2.0"
transformers:
- angular
- polymer:
    entry_points:
    - web/index.html
dependency_overrides:
  browser: any
  web_components: 0.4.0
  analyzer: ">=0.15.6 <0.16.0"
  html5lib: ">=0.11.0 <0.12.0"